services:
  shtytlkr:
    image: umdoobby/shtytlkr:latest
    container_name: shtytlkr
    restart: unless-stopped
    networks:
      - reverse-proxy
    ports:
      - "3001:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shtytlkr.rule=Host(`shtytlkr.your-awesome-site.com`)"
      - "traefik.http.routers.shtytlkr.entrypoints=websecure"
    environment:
      - PORT=3000
      - TELEGRAM_TOKEN=your-token-here
      - DOMAIN=shtytlkr.your-domain.com
      - WEBHOOK_PATH=/telegram-webhook-uri
      - SECRET_KEY=random-alphanumeric-string
      - CHAR_LIMIT=1000

networks:
  reverse-proxy:
    external: true